import { ChecklistItem, Project, ProjectChecklistResult, ReadinessSummary } from "./types";

export function generateItemFailureMarkdown(
  project: Project,
  item: ChecklistItem,
  result: ProjectChecklistResult
): string {
  const timestamp = result.updatedAt ? new Date(result.updatedAt).toISOString().replace("T", " ").slice(0, 16) : new Date().toISOString().replace("T", " ").slice(0, 16);

  return `### 🚨 Production Readiness Defect: [${item.code}] ${item.title}
- **Project**: ${project.name} (\`${project.version}\`)
- **Environment**: ${project.environment}
- **Category**: ${item.categoryId.replace(/-/g, " ").toUpperCase()}
- **Criticality**: ${item.criticality} (${item.priority} Blocker)
- **Status**: ${result.status.toUpperCase()}
- **Tester**: ${result.testerName || project.leadTester || "QA Team"} (${timestamp})
${project.deploymentUrl ? `- **Deployment**: ${project.deploymentUrl}\n` : ""}${project.repositoryUrl ? `- **Repository**: ${project.repositoryUrl}\n` : ""}
#### 🔍 Verification Guidance
${item.verificationGuide || item.description}

#### 📝 QA Findings & Notes
${result.notes ? result.notes : "_No additional freeform notes provided._"}

${result.expectedBehavior ? `**Expected Behavior**:\n${result.expectedBehavior}\n` : ""}
${result.actualBehavior ? `**Actual Behavior**:\n${result.actualBehavior}\n` : ""}
${result.stepsToReproduce ? `**Steps to Reproduce**:\n${result.stepsToReproduce}\n` : ""}
${result.evidenceUrl ? `**Evidence / Screenshot Link**:\n${result.evidenceUrl}\n` : ""}
---
_Generated by KAIROS Production Readiness & QA System_`;
}

export function generateFullProjectReportMarkdown(
  project: Project,
  items: ChecklistItem[],
  results: ProjectChecklistResult[],
  summary: ReadinessSummary
): string {
  const resultMap = new Map<string, ProjectChecklistResult>();
  results.forEach((r) => resultMap.set(r.itemId, r));

  const failedItems = items
    .filter((i) => resultMap.get(i.id)?.status === "failed")
    .map((i) => ({ item: i, result: resultMap.get(i.id)! }));

  const blockedItems = items
    .filter((i) => resultMap.get(i.id)?.status === "blocked")
    .map((i) => ({ item: i, result: resultMap.get(i.id)! }));

  const passedItems = items
    .filter((i) => resultMap.get(i.id)?.status === "passed")
    .map((i) => ({ item: i, result: resultMap.get(i.id)! }));

  const reportDate = new Date().toISOString().replace("T", " ").slice(0, 16);

  let md = `# 🛡️ KAIROS Production Readiness Assessment Report

**Project**: ${project.name}  
**Version**: \`${project.version}\`  
**Environment**: ${project.environment}  
**Lead QA**: ${project.leadTester}  
**Project Owner**: ${project.owner}  
**Assessment Date**: ${reportDate}  
${project.deploymentUrl ? `**Deployment URL**: ${project.deploymentUrl}  \n` : ""}${project.repositoryUrl ? `**Repository**: ${project.repositoryUrl}  \n` : ""}
---

## 📊 Executive Release Verdict

| Metric | Value |
| :--- | :--- |
| **Release Verdict** | **${summary.verdictLabel}** |
| **Deployable?** | **${summary.canDeploy ? "✅ YES - APPROVED FOR PRODUCTION" : "❌ NO - RELEASE BLOCKED"}** |
| **Passed Checks** | ${summary.passedCount} / ${summary.totalChecks - summary.notApplicableCount} (${summary.percentPassed}%) |
| **Failed Checks** | ${summary.failedCount} (Critical: ${summary.criticalFailedCount}, High: ${summary.highFailedCount}, Med/Low: ${summary.mediumFailedCount + summary.lowFailedCount}) |
| **Blocked Checks** | ${summary.blockedCount} |
| **Untested Remaining**| ${summary.untestedCount} |
| **N/A Excluded** | ${summary.notApplicableCount} |

---

`;

  if (summary.blockers.length > 0) {
    md += `## ⚠️ Active Release Blockers\n\n`;
    summary.blockers.forEach((b, idx) => {
      md += `${idx + 1}. **${b}**\n`;
    });
    md += `\n---\n\n`;
  }

  if (failedItems.length > 0) {
    md += `## ❌ Failed Checks & Defect Log (${failedItems.length})\n\n`;
    failedItems.forEach(({ item, result }) => {
      md += `### [${item.code}] ${item.title} \`[${item.criticality} - ${item.priority}]\`\n`;
      md += `- **Category**: ${item.categoryId.replace(/-/g, " ").toUpperCase()}\n`;
      if (result.notes) md += `- **Notes**: ${result.notes}\n`;
      if (result.expectedBehavior) md += `- **Expected**: ${result.expectedBehavior}\n`;
      if (result.actualBehavior) md += `- **Actual**: ${result.actualBehavior}\n`;
      if (result.stepsToReproduce) md += `- **Repro Steps**: ${result.stepsToReproduce}\n`;
      if (result.evidenceUrl) md += `- **Evidence**: ${result.evidenceUrl}\n`;
      md += `\n`;
    });
    md += `---\n\n`;
  }

  if (blockedItems.length > 0) {
    md += `## 🛑 Blocked Items (${blockedItems.length})\n\n`;
    blockedItems.forEach(({ item, result }) => {
      md += `- **[${item.code}] ${item.title}**: ${result.notes || "Marked as blocked during testing."}\n`;
    });
    md += `\n---\n\n`;
  }

  md += `## ✅ Verified Passed Checks (${passedItems.length})\n\n`;
  passedItems.slice(0, 30).forEach(({ item }) => {
    md += `- [x] **[${item.code}]** ${item.title}\n`;
  });
  if (passedItems.length > 30) {
    md += `- _...and ${passedItems.length - 30} additional passed checks._\n`;
  }

  md += `\n---\n_Report generated securely by KAIROS – Production Readiness & QA Checklist System_`;

  return md;
}
